Feature/pz 26 reusable card component
mindXcape/PHASE-ZERO-REVAMP pull request #10
Opened 2023-07-14 10:21 UTC by sarojghalan

# PZ-26-Reusable-Card-Component

## Summary of change
This PR is about creating Product Card. While creating this PR hold style, type and index file. Where style file is for styled components where different property of MUI is being used such as Stack, Image, Icon and wrapped inside styled. Type file consist required interface for the product card, where as index file contains overall arrangement of styled component,
![image](https://github.com/mindXcape/PHASE-ZERO-REVAMP/assets/88360959/0acb159c-1714-412e-b670-38921e49ebd1)

Changes ...

## Reviewers
Review:@Prashishgt  @dipeshkumarsah98 @subhashishjungshah 

Fixes: PZ-26

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] Front End (UI) changes

## How did you test
- [X] Tested the ui, how it will look by importing it in page.tsx file.
- [X] Tested the hover effect , and tested drawer opening feature while clicking in size button

## Checklist

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added required tests that prove my fix is effective or that my feature works
- [ ] Both New and Existing unit tests pass locally with my changes

2023-07-14 11:00 UTC, Prashishgt reviewed
Look into few comments i have left, other than that good work. keep up the grind.

2023-07-14 11:00 UTC, Prashishgt commented on components/PZCard/PZProductCard/index.tsx
> +  console.log(loading);
i don't think this is required, remove log after testing required data.

2023-07-14 11:00 UTC, Prashishgt commented on components/PZCard/PZProductCard/index.tsx
> +          key={keys}
same as subhu said, don't use keys as key, make additional data as id ex: id:1 size: Large so it takes thatt number

2023-07-14 11:00 UTC, Prashishgt commented on components/PZCard/PZProductCard/style.ts
> +  @media only screen and (min-width: 320px) and (max-width: 480px) {
is there a way we can create this dynamic, i am also running the same issue with this and forgot to mention it earlier. 
let look into dynamic approach ex: defining it into theme and make an standard same as mixins in previous iteration.

2023-07-14 11:00 UTC, Prashishgt commented on data/index.ts
> +export const PZSizes: string[] = ["S", "X", "L"];
use object and add id as additional attribute which will help in key

2023-07-14 11:00 UTC, Prashishgt commented on components/PZCard/PZProductCard/index.tsx
> +          <StyledPZProductImg src={imageBack} alt={`${title}`} />
i don't think template literal is required here, simple {title} should work, but look into it

2023-07-14 11:18 UTC, subhashishjungshah requested changes

2023-07-14 11:18 UTC, subhashishjungshah commented on components/PZCard/PZProductCard/index.tsx
> +  const PZFlexContainer = () => (
I think this should be outside and seperate then your main component in the same file

2023-07-14 11:18 UTC, subhashishjungshah commented on components/PZCard/PZProductCard/index.tsx
> +import { PZSizes } from "@/data";
Sizes will also come from backend. You can add them as props. Sizes will come in array format

2023-07-14 11:18 UTC, subhashishjungshah commented on components/PZCard/PZProductCard/index.tsx
> +export const PZProductCard = ({
Good take

2023-07-14 11:18 UTC, subhashishjungshah commented on components/PZCard/PZProductCard/index.tsx
> +          <StyledPZProductImg src={imageBack} alt={`${title}`} />
Good observation

2023-07-14 11:18 UTC, subhashishjungshah commented on data/index.ts
> +export const PZSizes: string[] = ["S", "X", "L"];
The data will from backend in this format. This is fine

2023-07-14 14:25 UTC, sarojghalan commented on components/PZCard/PZProductCard/index.tsx
> +          <StyledPZProductImg src={imageBack} alt={`${title}`} />
lovely

2023-07-14 14:25 UTC, sarojghalan commented on components/PZCard/PZProductCard/style.ts
> +  @media only screen and (min-width: 320px) and (max-width: 480px) {
oh lovely, lets work on together

2023-07-15 13:59 UTC, subhashishjungshah approved these changes
LGTM :rocket:

2023-07-15 13:59 UTC, subhashishjungshah commented on components/PZCard/PZProductCard/index.tsx
> +const PZFlexContainer = ({ sizes }: { sizes: string[] | undefined }) => (
Dont use undefined. If we use any or undefined, there is no meaning of using typescript

2023-07-16 05:03 UTC, subhashishjungshah requested changes

2023-07-16 05:03 UTC, subhashishjungshah commented on components/PZCard/PZProductCard/index.tsx
> +const PZFlexContainer = ({ sizes }: { sizes?: string[] }) => (
This will not work. This function will not be pure if you do this. I think you can do something like this below

2023-07-16 05:03 UTC, subhashishjungshah commented on components/PZCard/PZProductCard/index.tsx
> +        <PZFlexContainer sizes={sizes} />
here you can do sizes && <PZFlexContainer sizes={sizes} />. This will solve this ts problem.

2023-07-16 05:37 UTC, merged