Feature/pz 25 reusable button component
mindXcape/PHASE-ZERO-REVAMP pull request #3
Opened 2023-07-10 14:07 UTC by sarojghalan

# Merge Request : feature/pz 25 reusable button component

## Summary of change
In this pr i have created a styled component of button, where its types and interface are also created for type-checking, for more i have created a global theme provider to provide theme across the project, and a global theme which contains overall used color of the project.

## Mention

Review: @subhashishshah @dipeshkumarsah98 

Fixes: #task_issue_id

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [X] Front End (UI) changes
- [ ] Changes in `documentation`

## How did you test

- [ ] Tested the functionality of A
- [ ] Tested the functionality of B

## Checklist

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added required tests that prove my fix is effective or that my feature works
- [ ] Both New and Existing unit tests pass locally with my changes

2023-07-10 14:21 UTC, dipeshkumarsah98 commented on components/PZButton/style.ts
> +      border: 1px solid black !important;
while hovering cursor should be pointer

2023-07-10 14:31 UTC, dipeshkumarsah98 requested changes
Nice Work :+1: .The global theme is not passed to the app as a result compilation error is encountered. 
And formatting is not setup as well. use pretter to format the code. I'm getting error when i open you edited files. Resolve the mentioned issues and ask for re-review. Thank you
![image](https://github.com/mindXcape/PHASE-ZERO-REVAMP/assets/63381568/8a58ffd9-2301-444a-aa08-d4d9075ba744)

![image](https://github.com/mindXcape/PHASE-ZERO-REVAMP/assets/63381568/580fd4be-4f9f-469e-b248-9da643012fd7)

2023-07-10 18:10 UTC, sarojghalan commented on components/PZButton/style.ts
> +      border: 1px solid black !important;
sorry my bad.

2023-07-11 06:17 UTC, subhashishjungshah reviewed
@sarojghalan please resolve these comments!

2023-07-11 06:17 UTC, subhashishjungshah commented on app/layout.tsx
> +        <body className={inter.className}>
please remove this inter.classname. I think we aren't using this font.

2023-07-11 06:17 UTC, subhashishjungshah commented on components/PZButton/index.tsx
> +  <StyledPZButton className={`${className} ${variant}`} onClick={onClick}>
why aren't we using classname package?

2023-07-11 06:17 UTC, subhashishjungshah commented on components/PZButton/style.ts
> +  &.primary__btn {
okay there are alot of repeated css. for example, we need to group the same css in one place. Only the extra required for primary__btn should be written inside &.primary__btn and &.square__btn :100:

2023-07-11 06:17 UTC, subhashishjungshah commented on package.json
> +    "classnames": "^2.3.2",
please use this package if you have installed.

2023-07-11 06:17 UTC, subhashishjungshah commented on app/layout.tsx
>  import './globals.css'
what is inside ./globals.css?

2023-07-11 06:21 UTC, dipeshkumarsah98 commented on components/PZButton/style.ts
> +      border: 1px solid black !important;
when you solve the comment please click on a resolve conversation button to resolve the comment.

2023-07-11 06:33 UTC, dipeshkumarsah98 commented on components/PZButton/style.ts
> +  &.primary__btn {
variants name is passes a props in a component so it should be better to follow camelCase rule. like primaryButton.

2023-07-11 07:14 UTC, dipeshkumarsah98 commented on components/PZButton/style.ts
> +  &.square__btn {
use addittioanl props name as size where you pass the sizes such as 'sm', 'lg', 'md', 'xl'. And the variants should be common like primary, secondary

2023-07-11 12:04 UTC, sarojghalan reviewed
conversation resolved

2023-07-11 13:12 UTC, merged