Feature/reusable Drawer component
mindXcape/PHASE-ZERO-REVAMP pull request #4
Opened 2023-07-11 19:04 UTC by sarojghalan

# **Feature : Reusable DrawerComponent**

## Summary of change
As this file hasn't changed, but it has implemented new feature which is reusable drawer component. For that i have used a famous library named MUI.

## Mention

Review: @subhashishjungshah @dipeshkumarsah98 

Fixes: #task_issue_id

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [X] Front End (UI) changes
- [ ] Changes in `documentation`

## How did you test

- [ ] Tested the functionality of A
- [ ] Tested the functionality of B

## Checklist

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added required tests that prove my fix is effective or that my feature works
- [ ] Both New and Existing unit tests pass locally with my changes

2023-07-12 02:10 UTC, subhashishjungshah requested changes
@dipeshkumarsah98 I have reviewed and added comments. Overall it looks good :rocket: . Minor changes are expected. You can further review. Thank you

2023-07-12 02:10 UTC, subhashishjungshah commented on components/Drawer/DrawerProvider.tsx
> +      <Drawer
This component here is a material UI component. Are we allowed to use MUI component directly @dipeshkumarsah98 ? I also have to research in this thing.

2023-07-12 02:10 UTC, subhashishjungshah commented on components/Drawer/DrawerProvider.tsx
> +export default function DrawerProvider({
naming convention PZDrawer for consistency. All components should be similar

2023-07-12 02:10 UTC, subhashishjungshah commented on components/Drawer/DrawerProvider.tsx
> +      <PZButton
well done. Good use of our components. Only the naming convention is bad. BEM looks bad.

2023-07-12 02:10 UTC, subhashishjungshah commented on app/page.tsx
> +import { SearchIcon } from "@/public/icons";
For now its fine, but letter we should have different folder for icons

2023-07-12 02:10 UTC, subhashishjungshah commented on components/PZButton/type.ts
>  export interface IPZButtonProps {
okay again bad code writing habit. In drawer component you have used DrawerProviderI and here you have used IPZButtonProps. Please make rule where how should we name our interface?

2023-07-12 02:10 UTC, subhashishjungshah commented on public/icons/index.ts
> +import SearchIcon from "@mui/icons-material/Search";
This folder shouldnt be inside public. We consider icons as a component. It should be inside components. I will provide you references

2023-07-12 02:37 UTC, sarojghalan commented on app/page.tsx
> +import { SearchIcon } from "@/public/icons";
For icons i have already created file icons which is inside public folder, public folder i used for assests, icons . If there any better approach please feel free to add comment. Thank You.

2023-07-12 02:38 UTC, sarojghalan commented on components/Drawer/DrawerProvider.tsx
> +  const [state, setState] = React.useState({
Nice comment. Noted.

2023-07-12 02:41 UTC, sarojghalan commented on components/Drawer/DrawerProvider.tsx
> +      <Drawer
main purpose of drawer component is to make reusable, And drawer component is not being directly used in direct component, It takes children as a props. But i think there may be better approach for it.

2023-07-12 02:42 UTC, sarojghalan commented on public/icons/index.ts
> +import SearchIcon from "@mui/icons-material/Search";
nice, please .

2023-07-12 03:32 UTC, subhashishjungshah commented
Also Please use MR template properly. Alot things arent mention. Also provide screenshots for designs and responses @dipeshkumarsah98 @sarojghalan

2023-07-12 04:59 UTC, sarojghalan commented on components/Drawer/DrawerProvider.tsx
> +type Anchor = "top" | "left" | "bottom" | "right";
As long we are using this type in this single file,  and if this were styled component that would be best but this is just a provider.

2023-07-12 05:22 UTC, dipeshkumarsah98 commented on components/Drawer/DrawerProvider.tsx
> +  const toggleDrawer =
it will be better if you could comment out the complex logic.

2023-07-12 05:23 UTC, dipeshkumarsah98 commented on components/PZButton/index.tsx
> +import React from "react";
do we need react here ? is it necessary to import react ?

2023-07-12 05:23 UTC, dipeshkumarsah98 commented on components/PZButton/index.tsx
> +import classNames from "classnames";
yesterday we concluded that classNames should be used as a 'cn' in our whole project isn't it ?

2023-07-12 05:25 UTC, dipeshkumarsah98 commented on components/PZButton/style.ts
>    &.common__style {
I forget to mention in yesterday PR, that we don't need common style class. common_style class css should be provided without any class so that it will be parent for all the buttons.

2023-07-12 05:30 UTC, dipeshkumarsah98 commented on package.json
> +    "@mui/material": "^5.14.0",
You are installing new package and there is not separate commit for that !
if you don't use the atomic commit convention, sorry to say but PR won't get approved. And you have to write all the code again with proper atomic commit. So better you resolve this issue in next re-review. If you have to undo all the code and write it again, then do it but atomic commit should be implemented when you ask for re-review.

2023-07-12 05:37 UTC, dipeshkumarsah98 commented on components/Drawer/DrawerProvider.tsx
> +      <Drawer
You should import MUI component in style.ts file then override the CSS as per your requirement then import it in index.tsx then export for the whole app. This convention should strictly followed

2023-07-12 09:37 UTC, sarojghalan commented on package.json
> +    "@mui/material": "^5.14.0",
lovely

2023-07-12 14:01 UTC, dipeshkumarsah98 requested changes
@sarojghalan Nice work :clap: . I have noticed some of the changes which i have commented below. Resolve those comments and ask for re-review when you are done. Thank you.

2023-07-12 14:38 UTC, dipeshkumarsah98 commented on components/PZDrawer/index.tsx
> +        anchor={anchor}
Resolve this error with transient.
![image](https://github.com/mindXcape/PHASE-ZERO-REVAMP/assets/63381568/4507ca51-7e99-4235-843d-e7672d89252d)

2023-07-12 17:54 UTC, sarojghalan commented on components/PZDrawer/index.tsx
> +export default function PZDrawer({ children, anchor, icon }: PZDrawerPropsI) {
I think initial anchor state is setting their default value.

2023-07-13 11:19 UTC, sarojghalan commented on components/PZDrawer/index.tsx
> +        anchor={anchor}
That is just a warning

2023-07-13 11:57 UTC, dipeshkumarsah98 commented on components/PZDrawer/index.tsx
> +        anchor={anchor}
No warning should be there. use transient.

2023-07-13 12:26 UTC, merged